CSV_FILE = LOAD 'cssd1.csv' USING PigStorage (',') AS (ID, UA)
TSV_FILE = LOAD 'cssd2.tsv' USING PigStorage ('\t') AS (ID, COUNTRY, F1, F2, F3)
CSV_TSV_JOIN = JOIN CSV_FILE by ID, TSV_FILE by ID

INT_OUTPUT = FOREACH CSV_TSV_JOIN GENERATE CSV_FILE::ID, TSV_FILE::COUNTRY, CSV_FILE::UA, TSV_FILE::F1, TSV_FILE::F2, TSV_FILE::F3

EU_FILE = LOAD 'EuCountries.txt' USING PigStorage (',') AS (CODE, COUNTRY)
LEFT_JOIN_EU = JOIN INT_OUTPUT by COUNTRY LEFT OUTER, EU_FILE by CODE
RESULT = FILTER LEFT_JOIN_EU BY EU_FILE::CODE is null
STORE RESULT INTO ‘myoutput.txt’ using PigStorage(',');